/* =========================================================================
   Icon set — generated by build/icons.mjs, do not edit by hand.

   Path data from Tabler Icons (https://tabler.io/icons), MIT License,
   Copyright (c) 2020-2026 Paweł Kuna.

   Icons are built as real SVG nodes rather than emoji so they inherit
   currentColor and size predictably on every platform.
   ========================================================================= */

(() => {
  'use strict';
  const NS = (globalThis.TTSFlow = globalThis.TTSFlow || {});
  if (NS.icon) return;

  const PATHS = {
  "prev": {
    "inner": "<path d=\"M19.496 4.136l-12 7a1 1 0 0 0 0 1.728l12 7a1 1 0 0 0 1.504 -.864v-14a1 1 0 0 0 -1.504 -.864z\" /> <path d=\"M4 4a1 1 0 0 1 .993 .883l.007 .117v14a1 1 0 0 1 -1.993 .117l-.007 -.117v-14a1 1 0 0 1 1 -1z\" />",
    "filled": true
  },
  "play": {
    "inner": "<path d=\"M6 4v16a1 1 0 0 0 1.524 .852l13 -8a1 1 0 0 0 0 -1.704l-13 -8a1 1 0 0 0 -1.524 .852z\" />",
    "filled": true
  },
  "pause": {
    "inner": "<path d=\"M9 4h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h2a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2z\" /> <path d=\"M17 4h-2a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h2a2 2 0 0 0 2 -2v-12a2 2 0 0 0 -2 -2z\" />",
    "filled": true
  },
  "stop": {
    "inner": "<path d=\"M17 4h-10a3 3 0 0 0 -3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3 -3v-10a3 3 0 0 0 -3 -3z\" />",
    "filled": true
  },
  "next": {
    "inner": "<path d=\"M3 5v14a1 1 0 0 0 1.504 .864l12 -7a1 1 0 0 0 0 -1.728l-12 -7a1 1 0 0 0 -1.504 .864z\" /> <path d=\"M20 4a1 1 0 0 1 .993 .883l.007 .117v14a1 1 0 0 1 -1.993 .117l-.007 -.117v-14a1 1 0 0 1 1 -1z\" />",
    "filled": true
  },
  "close": {
    "inner": "<path d=\"M18 6l-12 12\" /> <path d=\"M6 6l12 12\" />",
    "filled": false
  },
  "trash": {
    "inner": "<path d=\"M4 7l16 0\" /> <path d=\"M10 11l0 6\" /> <path d=\"M14 11l0 6\" /> <path d=\"M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12\" /> <path d=\"M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3\" />",
    "filled": false
  },
  "download": {
    "inner": "<path d=\"M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2\" /> <path d=\"M7 11l5 5l5 -5\" /> <path d=\"M12 4l0 12\" />",
    "filled": false
  },
  "settings": {
    "inner": "<path d=\"M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065\" /> <path d=\"M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0\" />",
    "filled": false
  },
  "check": {
    "inner": "<path d=\"M5 12l5 5l10 -10\" />",
    "filled": false
  },
  "broom": {
    "inner": "<path d=\"M5 5a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v14a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2l0 -14\" /> <path d=\"M8 14a4 4 0 1 0 8 0a4 4 0 1 0 -8 0\" /> <path d=\"M8 6h.01\" /> <path d=\"M11 6h.01\" /> <path d=\"M14 6h2\" /> <path d=\"M8 14c1.333 -.667 2.667 -.667 4 0c1.333 .667 2.667 .667 4 0\" />",
    "filled": false
  },
  "speaker": {
    "inner": "<path d=\"M15 8a5 5 0 0 1 0 8\" /> <path d=\"M17.7 5a9 9 0 0 1 0 14\" /> <path d=\"M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5\" />",
    "filled": false
  },
  "voice": {
    "inner": "<path d=\"M15 12.9a5 5 0 1 0 -3.902 -3.9\" /> <path d=\"M15 12.9l-3.902 -3.899l-7.513 8.584a2 2 0 1 0 2.827 2.83l8.588 -7.515\" />",
    "filled": false
  },
  "speed": {
    "inner": "<path d=\"M5.636 19.364a9 9 0 1 1 12.728 0\" /> <path d=\"M16 9l-4 4\" />",
    "filled": false
  },
  "grip": {
    "inner": "<path d=\"M4 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /> <path d=\"M4 15a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /> <path d=\"M11 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /> <path d=\"M11 15a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /> <path d=\"M18 9a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" /> <path d=\"M18 15a1 1 0 1 0 2 0a1 1 0 1 0 -2 0\" />",
    "filled": false
  }
};

  const SVG_NS = 'http://www.w3.org/2000/svg';

  // size is applied via CSS (width/height: 1em) so icons track font-size.
  NS.icon = function icon(name, { size = 18, className = '' } = {}) {
    const spec = PATHS[name];
    const svg = document.createElementNS(SVG_NS, 'svg');
    svg.setAttribute('viewBox', '0 0 24 24');
    svg.setAttribute('width', String(size));
    svg.setAttribute('height', String(size));
    svg.setAttribute('aria-hidden', 'true');
    svg.setAttribute('focusable', 'false');
    if (className) svg.setAttribute('class', className);

    if (!spec) return svg;

    if (spec.filled) {
      svg.setAttribute('fill', 'currentColor');
      svg.setAttribute('stroke', 'none');
    } else {
      svg.setAttribute('fill', 'none');
      svg.setAttribute('stroke', 'currentColor');
      svg.setAttribute('stroke-width', '1.75');
      svg.setAttribute('stroke-linecap', 'round');
      svg.setAttribute('stroke-linejoin', 'round');
    }

    // Parsed rather than assigned as innerHTML: the source is generated
    // build output, but parsing keeps this free of markup assignment.
    const parsed = new DOMParser().parseFromString(
      `<svg xmlns="${SVG_NS}">${spec.inner}</svg>`,
      'image/svg+xml'
    );
    for (const child of Array.from(parsed.documentElement.childNodes)) {
      svg.appendChild(child);
    }
    return svg;
  };
})();
